<a href="https://colab.research.google.com/github/MAI-AIIU/deep-learning/blob/main/src/first-week/data-manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Metadata
**Name**  
> Naveed Ahmad Hematmal

**Assignment**    

> Data manipulation and data processing  

## Try X > Y and X < Y where X, Y are both some tensors (matrices)

First I am creating a tensor (matrix) of 2X4 dimensions

In [7]:
import torch

X = torch.arange(8, dtype=torch.float32).reshape((2,4))
Y = torch.tensor([[2.0, 1, 43, 4], [1, 2, 2, 3]])

In [8]:
X == Y

tensor([[False,  True, False, False],
        [False, False, False, False]])

R = X > Y

R(i,j) == true if X(i,j) is greater than Y(i,j), and is false otherwise

In [9]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True]])

R = X > Y

R(i,j) == true if X(i,j) is less than Y(i,j), and is false otherwise

In [10]:
X < Y

tensor([[ True, False,  True,  True],
        [False, False, False, False]])

## Creating two tensors (matrices) of differnt shapes, and trying X > Y, and X < Y with broadcasting

In [11]:
W = torch.arange(8, dtype=torch.float32).reshape((2,4))
Z = torch.tensor([[2.0, 1, 43, 4]])

W(2, 4) and Z(1, 4) --> so for X > Y, first it add same row as first row to match it as (2, 4), once both become W(2,4) and Z(2,4) then apply X > Y as usual

In [12]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True]])

W(2, 4) and Z(1, 4) --> so for X > Y, first it add same row as first row to match it as (2, 4), once both become W(2,4) and Z(2,4) then apply X > Y as usual

In [14]:
X < Y

tensor([[ True, False,  True,  True],
        [False, False, False, False]])